{{- if .Values.ingress.enabled -}}
{{- $fullName := include "hasura-helm3-chart.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "hasura-helm3-chart.labels" . | indent 4 }}
  annotations:
{{- if .Values.internal }}
    kubernetes.io/ingress.class: nginx-internal
{{- else }}
    kubernetes.io/ingress.class: nginx
{{- end }}
{{- if .Values.https }}
{{- if (eq .Values.httpsEnvironment "prod") }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
{{- else }}
    cert-manager.io/cluster-issuer: letsencrypt-staging
{{- end }}
{{- end }}
{{- with .Values.ingress.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if or (eq .Values.https true) .Values.ingress.tls }}
  tls:
    - hosts:
{{- if .Values.ingress.tls }}
  {{- range .Values.ingress.tls }}
      {{- range .hosts }}
      - {{ . }}
      {{- end }}
  {{- end }}
{{- end }}

{{- if .Values.https }}
      {{- if .Values.primaryDomain -}}
      {{- if .Values.primaryDomainSSL }}
      - {{ .Values.primaryDomain }}
      {{- end -}}
      {{- end -}}
      {{- if .Values.secondaryDomain -}}
      {{- if .Values.secondaryDomainSSL }}
      - {{ .Values.secondaryDomain }}
      {{- end -}}
{{- end }}
      secretName: {{ $fullName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
  {{- end }}
{{- if .Values.primaryDomain }}
    - host: {{ .Values.primaryDomain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
{{- if .Values.secondaryDomain }}
    - host: {{ .Values.secondaryDomain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{- end }}
{{- end }}
