# Default values for hasura-helm3-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
envAsMultiline:

hasura:
  metadataDatabaseUrl: "postgres://username:password@hostname:port/dbname"
  adminSecret: "Abcdefghij1"
  metadataDir: "metadata"
  migrationsDir: "migrations"
  enableRemoteSchemaPermissions: "true"
  gitRepository: "https://gitlab-ci-token:access-token@gitlab.de/user/repo.git"
  enableConsole: "false"

image:
  repository: hasura/graphql-engine
  pullPolicy: IfNotPresent
  tag: v2.0.9.cli-migrations-v3

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

livenessProbePath: /
readinessProbePath: /

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
   cpu: 2000m
   memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
