# Default values for hasura-helm3-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
envAsMultiline: |
  ENV1=ABC
  ENV2=DEF

hasura:
  metadataDatabaseUrl: "postgres://username:password@hostname:port/dbname"
  adminSecret: "Abcdefghij1"
  metadataDir: "metadata"
  migrationsDir: "migrations"
  enableRemoteSchemaPermissions: "true"
  gitRepository: "https://gitlab-ci-token:access-token@gitlab.de/user/repo.git"
  gitSshKey:
  enableConsole: "false"

image:
  repository: hasura/graphql-engine
  pullPolicy: IfNotPresent
  tag: v2.0.9.cli-migrations-v3

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

livenessProbePath: /healthz
readinessProbePath: /healthz

resources:
  limits:
   cpu: 2000m
   memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
